"""refactor Status

Revision ID: 21cde379b588
Revises: aa981213285c
Create Date: 2024-02-20 23:03:07.006967

"""
from typing import Sequence
from typing import Union


# revision identifiers, used by Alembic.
revision: str = "21cde379b588"
down_revision: Union[str, None] = "aa981213285c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
